A = int(input("Informe o valor de A: "))
B = int(input("Informe o valor de B: "))
C = int(input("Informe o valor de C: "))
D = int(input("Informe o valor de D: "))
E = int(input("Informe o valor de E: "))
print("Area do triangulo:", (B * C)/2)
print("Area do reatangulo: ",(A+B+C+D))
print("Raio do circulo:", (3.14*E*E))