PraticaGA = float(input("Digite o valor da Atividade Prática de Grau A: "))
TeoricaGA = float(input("Digite o valor da Atividade Teórica de Grau A: "))
ProvaLabGB = float(input("Digite o valor da Prova de Laboratório de Grau B: "))
TesteGB = float(input("Digite o valor do Teste: "))
TrabGB = float(input("Digite o valor do Trabalho extraclasse: "))
NotaGA = (PraticaGA * 0.45) + (TeoricaGA * 0.55)
NotaGB = (ProvaLabGB * 0.6) + (TesteGB * 0.2) + (TrabGB * 0.2)
Nota_Total = (NotaGA * 0.33) + (NotaGB * 0.67)
print("Nota final: " ,Nota_Total)