A = int(input("informe o valor de A: "))
B = int(input("informe o valor de B: "))
C = int(input("informe o valor de C: "))
VlrDelta = ((B**2)-(4*A*C))
X1 = (-B+VlrDelta**(1/2)) / (2*A)
X2 = (-B-VlrDelta**(1/2)) / (2*A)
print("**O Resultado da Equação é: ")
print("X¹: " , X1)
print("X²: ", X2)